name: Deploy 2 DigitalOcean

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  IMAGE_TAG_TEST: adm8/dsbc25-app:test
  IMAGE_TAG_PROD: adm8/dsbc25-app:prod

jobs:
  docker-build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: ./app
          load: true
          tags: ${{ env.IMAGE_TAG_TEST }}

      #      - name: Test
      #        run: |
      #          docker run --rm ${{ env.IMAGE_TAG_TEST }} pytest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_TAG_PROD }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      # copy docker-compose.yml
      - name: copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          source: "docker-compose.yml"
          target: "/app/"

      # copy nginx config
      - name: copy nginx config
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          source: "config/"
          target: "/app"

      # copy nginx certs
      - name: copy nginx certs
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          source: "certs/"
          target: "/app"